[package]
name = "rust-warp-jwt-yt"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
jsonwebtoken = "9.3.1"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0.12"
tokio = { version = "1", features = ["full"] }
warp = "0.3.7"
